name: test

on:
  push:
    branches:
      - mainnet
      - testnet
      - "feature/*"
      - "features/*"
  pull_request:
    branches:
      - mainnet
      - testnet
      - "feature/*"
      - "features/*"
      - "test/*"

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Hardhat compile
        run: yarn compile

      - name: Run Hardhat unit tests
        run: yarn test
